### ISSUE TITLE
Issue when run test

### ISSUE THREAD

**Issue by phongho01** [fireblocks/mpc-lib#5]
I clone this repo to test library, but when run ecdsa_online_test.cpp file, it throws error. 
`/test: symbol lookup error: ./test: undefined symbol: secp256k1_ecdsa_recoverable_signature_parse_compact`.
I also have other questions 
1. what is the purpose of derived key? And what are differences from public key that was generated before creating share keys?
2. What section of code that compute signature of parties to final signature? 
3. What is the purposes of chaincode data ?

**Comment by nadav-fireblocks** [comment]
You probably don't have `libsecp256k1` installed properly.

We've recently added support for: [running tests in Docker for multiple platforms](https://github.com/fireblocks/mpc-lib/tree/main/docker),
the code can be built using either [Makefile](https://github.com/fireblocks/mpc-lib/blob/main/README.md) or [CMake](https://github.com/fireblocks/mpc-lib/pull/13),
and its recommended to follow our [GitHub Actions](https://github.com/fireblocks/mpc-lib/blob/main/.github/workflows/test.yml) as an example of that.

To answer your other questions, further context might be required.

Derived keys, which you may encounter in [hd_derive.cpp](https://github.com/fireblocks/mpc-lib/blob/main/src/common/blockchain/mpc/hd_derive.cpp) normally refer to [BIP32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki) and to [BIP44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki). 
BIP32 also [explains](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#extended-keys) what is a "chain code".

These definitions are all compliant to what is commonly knows as a "Hierarchical Deterministic (HD) Wallet"

As for this question:
> What section of code that compute signature of parties to final signature?

The computation of the final signature itself is concluded in the final round of MPC, 
and it depends on results of prior rounds of MPC. 

As for pointing to the section of code, the answer changes between different signing protocols.
The most classical example can be seen here [get_cmp_signature](https://github.com/fireblocks/mpc-lib/blob/2a48865f43befe328e72a82cfd16f3111c90ae79/src/common/cosigner/cmp_ecdsa_online_signing_service.cpp#L394).
